**Quantum Kepler Exoplanet detection using Data Reupload and Multi-layered Architecture**

Ashish Arya,          Vivek Patil,            Rajatav,         Lakshika




**Problem Statement**
Astronomical data analysis has been a celebrated problem for classical machine learning.Exoplanet detection through astronomical data is known for its peculiar challenges for astronomers. Advances in telescope technology have made it possible to install telescopes in space to obtain images from objects lightyears away. However this has given rise to humongous datasets which are difficult to analyse and interpret.
 
Kepler telescope was commissioned in 2009 for detection of exoplanets. Over the years the dataset obtained from the Kepler telescope has gained a reputation in astronomical data analysis similar to MNIST dataset in statistical data analysis. 
 
In recent times, state-of-the-art machine learning approaches including k-nearest neighbour, Principal Component Analysis, Convolution Neural Network, Recurrent Neural Network have been applied to the Kepler's noisy dataset. The results have been encouraging. However they suffer from lack of faster execution and complicated algorithms.The analysis of Kepler astronomical data is  prone to high number of false positives. 
 
Quantum Computing is the latest addition in the line of emerging technologies proving to be a viable solution for the complex problems which take years for classical supercomputer to solve. 
 
Since nearly all latest exoplanet discoveries are made using data science coupled with new approaches. In the year 2020 alone, 261 exoplanets were detected. 
 
Given the specific nature of the Kepler dataset, it is evident to employ techniques of Quantum Computing to take advantage of its inherent parallelism. Quantum entanglement and superposition could prove beneficial to analyse Kepler dataset in faster duration avoiding spurious detection.







**Solution Statement**
 
 
We have approached the problem of exoplanet detection from the Kepler dataset from a Quantum Computing perspective specifically considering the limit on uses of qubits and faithful representation of data fed into the Quantum Circuit.
 
The Kepler dataset has 9564 rows and 50 columns consisting of observations of sensors as well as a few derived parameters. The dataset is subjected to null values. The labels were in three categories Confirmed, Candidate and False positive. 
 
During pre-processing of the data, labels were converted to binary [0,1] and null values were removed. Out of 49 features of the datasets, most relevant 4 (and 6) features were selected.
 
Date reuploading concept uses a single qubit to represent arbitrarily high dimensional data. Multi-layers learning model strategy allows us to train the Quantum classifier circuit avoiding the problem of barren plateaus and achieve lesser depth circuits successfully. 
In the processing of training the model we used Variational Quantum Circuit for Data reuploading in a five layered quantum network. Each layer has been trained separately using the dataset. Mean-squared-error has been used as the cost function for training the network. 
We performed the simulation of the proposed Quantum network using (i) 4 features and to test the efficiency of the network (ii) 6 features. It was found the 4 features were giving better accuracy and loss values than the network using 6 features. The overall speed of the Quantum network was much faster than its classical counterparts.



In [6]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [7]:
dataset = pd.read_csv('/content/sample_data/exoplanets_2018.csv') 
#dataset = dataset.rename(columns=header_list)
dataset.head()

kepid kepoi_name   kepler_name  ...         ra        dec  koi_kepmag
0  10797460  K00752.01  Kepler-227 b  ...  291.93423  48.141651      15.347
1  10797460  K00752.02  Kepler-227 c  ...  291.93423  48.141651      15.347
2  10811496  K00753.01           NaN  ...  297.00482  48.134129      15.436
3  10848459  K00754.01           NaN  ...  285.53461  48.285210      15.597
4  10854555  K00755.01  Kepler-664 b  ...  288.75488  48.226200      15.509

[5 rows x 49 columns]

In [8]:
pd.set_option("display.max_columns", None)

In [9]:
dataset=dataset[['koi_disposition','koi_fpflag_nt','koi_fpflag_ss','koi_fpflag_co','koi_fpflag_ec']]

In [10]:
for col in dataset.columns:
    print(col)

koi_disposition
koi_fpflag_nt
koi_fpflag_ss
koi_fpflag_co
koi_fpflag_ec


In [11]:
dataset["koi_disposition"].replace({"CONFIRMED": "1", "CANDIDATE": "0", "FALSE POSITIVE": "0"}, inplace=True)
dataset.isnull().sum().sum()
dataset=dataset.dropna()
dataset["koi_disposition"].value_counts()

0    7207
1    2357
Name: koi_disposition, dtype: int64

In [12]:
dataset.head()

koi_disposition  koi_fpflag_nt  koi_fpflag_ss  koi_fpflag_co  koi_fpflag_ec
0               1              0              0              0              0
1               1              0              0              0              0
2               0              0              0              0              0
3               0              0              1              0              0
4               1              0              0              0              0

In [13]:
dataset = dataset.to_numpy()

# Sepparating the label (Y) from the input features (X)
Y = dataset[:, 0]
Y = np.array(Y, dtype=int)
X = dataset[:, 1:]

# Sanity check
print(X.shape, Y.shape)

(9564, 4) (9564,)


In [ ]:
#@title Hidden
# Separate data with label 0 and label 1

x_0 = X[Y == 0, :]
x_1 = X[Y == 1, :]
y_0 = Y[Y==0]
y_1 = Y[Y==1]

# Sanity check
print(x_0.shape, y_0.shape)
print(x_1.shape, y_1.shape)

In [14]:
# Split 70% of the data for training set and 30% for testing set

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=2001, shuffle=True, stratify=Y)
# x_train_1, x_test_1, y_train_1, y_test_1 = train_test_split(x_1, y_1, test_size=0.3, random_state=2001,shuffle=True, stratify=Y)
print(X_train.shape, Y_train.shape)
print(X_test.shape, Y_test.shape)

(6694, 4) (6694,)
(2870, 4) (2870,)


In [ ]:
#@title Hidden
num_sample = 1500 # sample per class, total = 5000

# Take the first 5000 samples (1500 from each class) from training set for X_train and Y_train
X_train = np.concatenate((x_train_0[:num_sample, :], x_train_1[:num_sample, :]), axis=0)
Y_train = np.concatenate((y_train_0[:num_sample], y_train_1[:num_sample]), axis=0)

# Take the first 5000 samples (1500 from each class) from testing set for X_test and Y_test
X_test = np.concatenate((x_test_0[:num_sample, :], x_test_1[:num_sample, :]), axis=0)
Y_test = np.concatenate((y_test_0[:num_sample], y_test_1[:num_sample]), axis=0)

# Manual Check 
print(X_train.shape, Y_train.shape)
print(X_test.shape, Y_test.shape)

In [15]:
#Save extracted datasets on the disk
#!mkdir 'KeplerDataset'

np.savetxt('/content/sample_data/X_train_6694.txt', X_train)
np.savetxt('/content/sample_data/X_test_2870.txt', X_test)
np.savetxt('/content/sample_data/Y_train_6694.txt', Y_train)
np.savetxt('/content/sample_data/Y_test_2870.txt', Y_test)

In [16]:
#@title Hidden
# Code to load the saved subset


X_train = np.loadtxt('/content/sample_data/X_train_6694.txt')
Y_train = np.loadtxt('/content/sample_data/Y_train_6694.txt')

X_test = np.loadtxt('/content/sample_data/X_test_2870.txt')
Y_test = np.loadtxt('/content/sample_data/Y_test_2870.txt')

# Check
print(X_train.shape, Y_train.shape)
print(X_test.shape, Y_test.shape)

(6694, 4) (6694,)
(2870, 4) (2870,)


In [19]:
#Training the Quantum Circuit in Simulator
!pip install pennylane
import pennylane as qml
from pennylane import numpy as np
from pennylane.optimize import AdamOptimizer

import tensorflow as tf
from tensorflow.keras.utils import to_categorical


     |████████████████████████████████| 460kB 6.6MB/s 


In [20]:
# Set a random seed
np.random.seed(42)

In [21]:
# Define output labels as quantum state vectors
label_0 = [[1], [0]]
label_1 = [[0], [1]]


def density_matrix(state):
    """Calculates the density matrix representation of a state.

    Args:
        state (array[complex]): array representing a quantum state vector

    Returns:
        dm: (array[complex]): array representing the density matrix
    """
    return np.outer(state,  np.conj(state))

state_labels = [label_0, label_1]
dm_labels = [density_matrix(state_labels[i]) for i in range(2)]

In [22]:
from keras import backend as K


# Alpha Custom Layer
class class_weights(tf.keras.layers.Layer):
    def __init__(self):
        super(class_weights, self).__init__()
        w_init = tf.random_normal_initializer()
        self.w = tf.Variable(
            initial_value=w_init(shape=(1, 2), dtype="float32"),
            trainable=True,
        )

    def call(self, inputs):
        return (inputs * self.w)

In [23]:
from keras import backend as K


# Alpha Custom Layer
class class_weights(tf.keras.layers.Layer):
    def __init__(self):
        super(class_weights, self).__init__()
        w_init = tf.random_normal_initializer()
        self.w = tf.Variable(
            initial_value=w_init(shape=(1, 2), dtype="float32"),
            trainable=True,
        )

    def call(self, inputs):
        return (inputs * self.w)

In [24]:
num_fc_layer = 5 # number of layer
params_fix = np.random.uniform(size=(2, num_fc_layer, 4))
print(params_fix)

[[[0.37454012 0.95071431 0.73199394 0.59865848]
  [0.15601864 0.15599452 0.05808361 0.86617615]
  [0.60111501 0.70807258 0.02058449 0.96990985]
  [0.83244264 0.21233911 0.18182497 0.18340451]
  [0.30424224 0.52475643 0.43194502 0.29122914]]

 [[0.61185289 0.13949386 0.29214465 0.36636184]
  [0.45606998 0.78517596 0.19967378 0.51423444]
  [0.59241457 0.04645041 0.60754485 0.17052412]
  [0.06505159 0.94888554 0.96563203 0.80839735]
  [0.30461377 0.09767211 0.68423303 0.44015249]]]


In [25]:
n_qubits = 2  # number of class
dev_fc = qml.device("default.qubit", wires=n_qubits)
layer_id = 0 # the layer index to be trained, it starts from zero because of Numpy convention

@qml.qnode(dev_fc)
def q_fc(params, inputs):
    """A variational quantum circuit representing the DRC.

    Args:
        params (array[float]): array of parameters
        inputs (array[float]): 1-d input vector (data sample)

    Returns:
        array[float]: 1-d output vector in the form of [alpha0*<O0>, alpha1*<O1>]
    """
    
    # layer iteration
    for l in range(len(params_fix[0])):
        # qubit iteration
        for q in range(n_qubits):
            # gate iteration
            for g in range(int(len(inputs)/3)):
              if l == layer_id: # train only the specified layer
                qml.Rot(*(params[0][3*g:3*(g+1)] * inputs[3*g:3*(g+1)] + params[1][3*g:3*(g+1)]), wires=q)
              else:
                qml.Rot(*(params_fix[0][l][3*g:3*(g+1)] * inputs[3*g:3*(g+1)] + params_fix[1][l][3*g:3*(g+1)]), wires=q)
    
    return [qml.expval(qml.Hermitian(dm_labels[i], wires=[i])) for i in range(n_qubits)]

In [26]:
n_component = 4 # number of features used

X = tf.keras.Input(shape=(n_component,), name='Input_Layer')


# Quantum Layer
q_fc_layer = qml.qnn.KerasLayer(q_fc, {"params": (2, n_component)}, output_dim=2)(X)

# Alpha Layer
alpha_layer = class_weights()(q_fc_layer)

model = tf.keras.Model(inputs=X, outputs=alpha_layer)

In [45]:
opt = tf.keras.optimizers.Adam(learning_rate=0.05)
model.compile(opt, loss='mse', metrics=["accuracy"])

In [46]:
filepath = "/content/sample_data/Best4_layer5(layer_id=0)_set1000_8epoch_saved-model-{epoch:02d}.hdf5"
checkpoint = tf.keras.callbacks.ModelCheckpoint(filepath, monitor='val_acc', verbose=1,
                                                save_weights_only=True, save_best_only=False, mode='auto')

In [47]:
H = model.fit(X_train, to_categorical(Y_train), epochs=3, batch_size=256, initial_epoch=0,
              validation_data=(X_test, to_categorical(Y_test)), verbose=1,
              callbacks=[checkpoint])

Epoch 1/3
27/27 [==============================] - 532s 20s/step - loss: 0.2508 - accuracy: 0.7504 - val_loss: 0.1404 - val_accuracy: 0.7537

Epoch 00001: saving model to /content/sample_data/Best4_layer5(layer_id=0)_set1000_8epoch_saved-model-01.hdf5
Epoch 2/3
27/27 [==============================] - 502s 19s/step - loss: 0.1390 - accuracy: 0.7535 - val_loss: 0.1328 - val_accuracy: 0.7537

Epoch 00002: saving model to /content/sample_data/Best4_layer5(layer_id=0)_set1000_8epoch_saved-model-02.hdf5
Epoch 3/3
27/27 [==============================] - 537s 20s/step - loss: 0.1336 - accuracy: 0.7535 - val_loss: 0.1320 - val_accuracy: 0.7537

Epoch 00003: saving model to /content/sample_data/Best4_layer5(layer_id=0)_set1000_8epoch_saved-model-03.hdf5


In [43]:
!pwd
!rm -rf /content/sample_data/Best*

/content


In [48]:
model.load_weights('/content/sample_data/Best4_layer5(layer_id=0)_set1000_8epoch_saved-model-03.hdf5')
#"/content/sample_data/Best4_layer5(layer_id=0)_set1000_8epoch_saved-model-{epoch:02d}.hdf5"

# keep that parameters and replace the initial one
params_layer_0 = model.get_weights()[0]
params_fix[:, 0, :] = params_layer_0

**2nd Layer**

In [49]:
n_qubits = 2  # number of class
dev_fc = qml.device("default.qubit", wires=n_qubits)
layer_id = 1 # the layer index to be trained, it starts from zero because of Numpy convention

@qml.qnode(dev_fc)
def q_fc(params, inputs):
    """A variational quantum circuit representing the DRC.

    Args:
        params (array[float]): array of parameters
        inputs (array[float]): 1-d input vector (data sample)

    Returns:
        array[float]: 1-d output vector in the form of [alpha0*<O0>, alpha1*<O1>]
    """
    
    # layer iteration
    for l in range(len(params_fix[0])):
        # qubit iteration
        for q in range(n_qubits):
            # gate iteration
            for g in range(int(len(inputs)/3)):
              if l == layer_id: # train only the specified layer
                qml.Rot(*(params[0][3*g:3*(g+1)] * inputs[3*g:3*(g+1)] + params[1][3*g:3*(g+1)]), wires=q)
              else:
                qml.Rot(*(params_fix[0][l][3*g:3*(g+1)] * inputs[3*g:3*(g+1)] + params_fix[1][l][3*g:3*(g+1)]), wires=q)
    
    return [qml.expval(qml.Hermitian(dm_labels[i], wires=[i])) for i in range(n_qubits)]

In [50]:
n_component = 4 # number of features used

X = tf.keras.Input(shape=(n_component,), name='Input_Layer')


# Quantum Layer
q_fc_layer = qml.qnn.KerasLayer(q_fc, {"params": (2, n_component)}, output_dim=2)(X)

# Alpha Layer
alpha_layer = class_weights()(q_fc_layer)

model = tf.keras.Model(inputs=X, outputs=alpha_layer)

In [51]:
opt = tf.keras.optimizers.Adam(learning_rate=0.05)
model.compile(opt, loss='mse', metrics=["accuracy"])

In [53]:
# Note: please put the correct directory to save the weights accordingly if you want to run the code
filepath = "/content/sample_data/Best4_layer5(layer_id=1)_set1000_8epoch_saved-model-{epoch:02d}.hdf5"

checkpoint = tf.keras.callbacks.ModelCheckpoint(filepath, monitor='val_acc', verbose=1,
                                                save_weights_only=True, save_best_only=False, mode='auto')

In [54]:
H = model.fit(X_train, to_categorical(Y_train), epochs=3, batch_size=256, initial_epoch=0,
              validation_data=(X_test, to_categorical(Y_test)), verbose=1,
              callbacks=[checkpoint])

Epoch 1/3
27/27 [==============================] - 539s 20s/step - loss: 0.2354 - accuracy: 0.7535 - val_loss: 0.1453 - val_accuracy: 0.7537

Epoch 00001: saving model to /content/sample_data/Best4_layer5(layer_id=1)_set1000_8epoch_saved-model-01.hdf5
Epoch 2/3
27/27 [==============================] - 534s 20s/step - loss: 0.1423 - accuracy: 0.7535 - val_loss: 0.1387 - val_accuracy: 0.7540

Epoch 00002: saving model to /content/sample_data/Best4_layer5(layer_id=1)_set1000_8epoch_saved-model-02.hdf5
Epoch 3/3
27/27 [==============================] - 531s 20s/step - loss: 0.1393 - accuracy: 0.7535 - val_loss: 0.1389 - val_accuracy: 0.7537

Epoch 00003: saving model to /content/sample_data/Best4_layer5(layer_id=1)_set1000_8epoch_saved-model-03.hdf5


In [55]:
# load the parameters that is considered giving the best balance between train and test accuracy
#model.load_weights('./Model/Best6_layer5(layer_id=1)_set5000_10epoch_saved-model-08.hdf5')
model.load_weights('/content/sample_data/Best4_layer5(layer_id=1)_set1000_8epoch_saved-model-03.hdf5')


# keep that parameters and replace the initial one
params_layer_1 = model.get_weights()[0]
params_fix[:, 1, :] = params_layer_1

**3rd Layer**

In [56]:
n_qubits = 2  # number of class
dev_fc = qml.device("default.qubit", wires=n_qubits)
layer_id = 2 # the layer index to be trained, it starts from zero because of Numpy convention

@qml.qnode(dev_fc)
def q_fc(params, inputs):
    """A variational quantum circuit representing the DRC.

    Args:
        params (array[float]): array of parameters
        inputs (array[float]): 1-d input vector (data sample)

    Returns:
        array[float]: 1-d output vector in the form of [alpha0*<O0>, alpha1*<O1>]
    """
    
    # layer iteration
    for l in range(len(params_fix[0])):
        # qubit iteration
        for q in range(n_qubits):
            # gate iteration
            for g in range(int(len(inputs)/3)):
              if l == layer_id: # train only the specified layer
                qml.Rot(*(params[0][3*g:3*(g+1)] * inputs[3*g:3*(g+1)] + params[1][3*g:3*(g+1)]), wires=q)
              else:
                qml.Rot(*(params_fix[0][l][3*g:3*(g+1)] * inputs[3*g:3*(g+1)] + params_fix[1][l][3*g:3*(g+1)]), wires=q)
    
    return [qml.expval(qml.Hermitian(dm_labels[i], wires=[i])) for i in range(n_qubits)]

In [57]:
n_component = 4 # number of features used

X = tf.keras.Input(shape=(n_component,), name='Input_Layer')


# Quantum Layer
q_fc_layer = qml.qnn.KerasLayer(q_fc, {"params": (2, n_component)}, output_dim=2)(X)

# Alpha Layer
alpha_layer = class_weights()(q_fc_layer)

model = tf.keras.Model(inputs=X, outputs=alpha_layer)

In [58]:
opt = tf.keras.optimizers.Adam(learning_rate=0.05)
model.compile(opt, loss='mse', metrics=["accuracy"])

In [59]:
# Note: please put the correct directory to save the weights accordingly if you want to run the code
#filepath = "./Model/Best6_layer5(layer_id=2)_set5000_10epoch_saved-model-{epoch:02d}.hdf5"
filepath = "/content/sample_data/Best4_layer5(layer_id=2)_set1000_8epoch_saved-model-{epoch:02d}.hdf5"

checkpoint = tf.keras.callbacks.ModelCheckpoint(filepath, monitor='val_acc', verbose=1,
                                                save_weights_only=True, save_best_only=False, mode='auto')

In [60]:
H = model.fit(X_train, to_categorical(Y_train), epochs=3, batch_size=256, initial_epoch=0,
              validation_data=(X_test, to_categorical(Y_test)), verbose=1,
              callbacks=[checkpoint])

Epoch 1/3
27/27 [==============================] - 524s 20s/step - loss: 0.2575 - accuracy: 0.7305 - val_loss: 0.1419 - val_accuracy: 0.7537

Epoch 00001: saving model to /content/sample_data/Best4_layer5(layer_id=2)_set1000_8epoch_saved-model-01.hdf5
Epoch 2/3
27/27 [==============================] - 493s 18s/step - loss: 0.1411 - accuracy: 0.7523 - val_loss: 0.1349 - val_accuracy: 0.7540

Epoch 00002: saving model to /content/sample_data/Best4_layer5(layer_id=2)_set1000_8epoch_saved-model-02.hdf5
Epoch 3/3
27/27 [==============================] - 493s 18s/step - loss: 0.1353 - accuracy: 0.7535 - val_loss: 0.1333 - val_accuracy: 0.7540

Epoch 00003: saving model to /content/sample_data/Best4_layer5(layer_id=2)_set1000_8epoch_saved-model-03.hdf5


In [61]:
# load the parameters that is considered giving the best balance between train and test accuracy
#model.load_weights('./Model/Best6_layer5(layer_id=2)_set5000_10epoch_saved-model-08.hdf5')
model.load_weights('/content/sample_data/Best4_layer5(layer_id=2)_set1000_8epoch_saved-model-03.hdf5')


# keep that parameters and replace the initial one
params_layer_2 = model.get_weights()[0]
params_fix[:, 2, :] = params_layer_2

**4th Layer**

In [62]:
n_qubits = 2  # number of class
dev_fc = qml.device("default.qubit", wires=n_qubits)
layer_id = 3 # the layer index to be trained, it starts from zero because of Numpy convention

@qml.qnode(dev_fc)
def q_fc(params, inputs):
    """A variational quantum circuit representing the DRC.

    Args:
        params (array[float]): array of parameters
        inputs (array[float]): 1-d input vector (data sample)

    Returns:
        array[float]: 1-d output vector in the form of [alpha0*<O0>, alpha1*<O1>]
    """
    
    # layer iteration
    for l in range(len(params_fix[0])):
        # qubit iteration
        for q in range(n_qubits):
            # gate iteration
            for g in range(int(len(inputs)/3)):
              if l == layer_id: # train only the specified layer
                qml.Rot(*(params[0][3*g:3*(g+1)] * inputs[3*g:3*(g+1)] + params[1][3*g:3*(g+1)]), wires=q)
              else:
                qml.Rot(*(params_fix[0][l][3*g:3*(g+1)] * inputs[3*g:3*(g+1)] + params_fix[1][l][3*g:3*(g+1)]), wires=q)
    
    return [qml.expval(qml.Hermitian(dm_labels[i], wires=[i])) for i in range(n_qubits)]

In [63]:
n_component = 4 # number of features used

X = tf.keras.Input(shape=(n_component,), name='Input_Layer')


# Quantum Layer
q_fc_layer = qml.qnn.KerasLayer(q_fc, {"params": (2, n_component)}, output_dim=2)(X)

# Alpha Layer
alpha_layer = class_weights()(q_fc_layer)

model = tf.keras.Model(inputs=X, outputs=alpha_layer)

In [64]:
opt = tf.keras.optimizers.Adam(learning_rate=0.05)
model.compile(opt, loss='mse', metrics=["accuracy"])

In [65]:
# Note: please put the correct directory to save the weights accordingly if you want to run the code
filepath = "/content/sample_data/Best4_layer5(layer_id=3)_set1000_8epoch_saved-model-{epoch:02d}.hdf5"

checkpoint = tf.keras.callbacks.ModelCheckpoint(filepath, monitor='val_acc', verbose=1,
                                                save_weights_only=True, save_best_only=False, mode='auto')

In [66]:
H = model.fit(X_train, to_categorical(Y_train), epochs=3, batch_size=256, initial_epoch=0,
              validation_data=(X_test, to_categorical(Y_test)), verbose=1,
              callbacks=[checkpoint])

Epoch 1/3
27/27 [==============================] - 530s 20s/step - loss: 0.2756 - accuracy: 0.6521 - val_loss: 0.1406 - val_accuracy: 0.7540

Epoch 00001: saving model to /content/sample_data/Best4_layer5(layer_id=3)_set1000_8epoch_saved-model-01.hdf5
Epoch 2/3
27/27 [==============================] - 521s 19s/step - loss: 0.1381 - accuracy: 0.7426 - val_loss: 0.1313 - val_accuracy: 0.7537

Epoch 00002: saving model to /content/sample_data/Best4_layer5(layer_id=3)_set1000_8epoch_saved-model-02.hdf5
Epoch 3/3
27/27 [==============================] - 500s 19s/step - loss: 0.1321 - accuracy: 0.7438 - val_loss: 0.1308 - val_accuracy: 0.7537

Epoch 00003: saving model to /content/sample_data/Best4_layer5(layer_id=3)_set1000_8epoch_saved-model-03.hdf5


In [67]:
# load the parameters that is considered giving the best balance between train and test accuracy
#model.load_weights('./Model/Best6_layer5(layer_id=3)_set5000_10epoch_saved-model-08.hdf5')
model.load_weights('/content/sample_data/Best4_layer5(layer_id=3)_set1000_8epoch_saved-model-03.hdf5')


# keep that parameters and replace the initial one
params_layer_3 = model.get_weights()[0]
params_fix[:, 3, :] = params_layer_3



**5th Layer**

In [68]:
n_qubits = 2  # number of class
dev_fc = qml.device("default.qubit", wires=n_qubits)
layer_id = 4 # the layer index to be trained, it starts from zero because of Numpy convention

@qml.qnode(dev_fc)
def q_fc(params, inputs):
    """A variational quantum circuit representing the DRC.

    Args:
        params (array[float]): array of parameters
        inputs (array[float]): 1-d input vector (data sample)

    Returns:
        array[float]: 1-d output vector in the form of [alpha0*<O0>, alpha1*<O1>]
    """
    
    # layer iteration
    for l in range(len(params_fix[0])):
        # qubit iteration
        for q in range(n_qubits):
            # gate iteration
            for g in range(int(len(inputs)/3)):
              if l == layer_id: # train only the specified layer
                qml.Rot(*(params[0][3*g:3*(g+1)] * inputs[3*g:3*(g+1)] + params[1][3*g:3*(g+1)]), wires=q)
              else:
                qml.Rot(*(params_fix[0][l][3*g:3*(g+1)] * inputs[3*g:3*(g+1)] + params_fix[1][l][3*g:3*(g+1)]), wires=q)
    
    return [qml.expval(qml.Hermitian(dm_labels[i], wires=[i])) for i in range(n_qubits)]

In [69]:
n_component = 4 # number of features used

X = tf.keras.Input(shape=(n_component,), name='Input_Layer')


# Quantum Layer
q_fc_layer = qml.qnn.KerasLayer(q_fc, {"params": (2, n_component)}, output_dim=2)(X)

# Alpha Layer
alpha_layer = class_weights()(q_fc_layer)

model = tf.keras.Model(inputs=X, outputs=alpha_layer)

In [70]:
opt = tf.keras.optimizers.Adam(learning_rate=0.05)
model.compile(opt, loss='mse', metrics=["accuracy"])

In [71]:
# Note: please put the correct directory to save the weights accordingly if you want to run the code
filepath = "/content/sample_data/Best4_layer5(layer_id=4)_set1000_8epoch_saved-model-{epoch:02d}.hdf5"

checkpoint = tf.keras.callbacks.ModelCheckpoint(filepath, monitor='val_acc', verbose=1,
                                                save_weights_only=True, save_best_only=False, mode='auto')

In [72]:
H = model.fit(X_train, to_categorical(Y_train), epochs=3, batch_size=256, initial_epoch=0,
              validation_data=(X_test, to_categorical(Y_test)), verbose=1,
              callbacks=[checkpoint])

Epoch 1/3
27/27 [==============================] - 490s 18s/step - loss: 0.2442 - accuracy: 0.7535 - val_loss: 0.1327 - val_accuracy: 0.7328

Epoch 00001: saving model to /content/sample_data/Best4_layer5(layer_id=4)_set1000_8epoch_saved-model-01.hdf5
Epoch 2/3
27/27 [==============================] - 499s 19s/step - loss: 0.1347 - accuracy: 0.7422 - val_loss: 0.1313 - val_accuracy: 0.7537

Epoch 00002: saving model to /content/sample_data/Best4_layer5(layer_id=4)_set1000_8epoch_saved-model-02.hdf5
Epoch 3/3
27/27 [==============================] - 526s 20s/step - loss: 0.1321 - accuracy: 0.7535 - val_loss: 0.1307 - val_accuracy: 0.7537

Epoch 00003: saving model to /content/sample_data/Best4_layer5(layer_id=4)_set1000_8epoch_saved-model-03.hdf5


In [73]:
# load the parameters that is considered giving the best balance between train and test accuracy
#model.load_weights('./Model/Best6_layer5(layer_id=4)_set5000_10epoch_saved-model-08.hdf5')
model.load_weights('/content/sample_data/Best4_layer5(layer_id=4)_set1000_8epoch_saved-model-03.hdf5')


# keep that parameters and replace the initial one
params_layer_4 = model.get_weights()[0]
params_fix[:, 4, :] = params_layer_4

**Final Training**

In [ ]:
n_qubits = 2  # number of class
dev_fc = qml.device("default.qubit", wires=n_qubits)

@qml.qnode(dev_fc)
def q_fc(params, inputs):
    """A variational quantum circuit representing the DRC.

    Args:
        params (array[float]): array of parameters
        inputs (array[float]): 1-d input vector (data sample)

    Returns:
        array[float]: 1-d output vector in the form of [alpha0*<O0>, alpha1*<O1>]
    """
    
    # layer iteration
    for l in range(len(params[0])):
        # qubit iteration
        for q in range(n_qubits):
            # gate iteration
            for g in range(int(len(inputs)/3)):
              qml.Rot(*(params[0][l][3*g:3*(g+1)] * inputs[3*g:3*(g+1)] + params[1][l][3*g:3*(g+1)]), wires=q)
    
    return [qml.expval(qml.Hermitian(dm_labels[i], wires=[i])) for i in range(n_qubits)]

In [ ]:
n_component = 6

X = tf.keras.Input(shape=(n_component,), name='Input_Layer')


# Quantum Layer
num_fc_layer = 5
q_fc_layer = qml.qnn.KerasLayer(q_fc, {"params": (2, num_fc_layer, n_component)}, output_dim=2)(X)

# Alpha Layer
alpha_layer = class_weights()(q_fc_layer)

model = tf.keras.Model(inputs=X, outputs=alpha_layer)

In [ ]:
# view each of the layer's name and its specifications
model.summary()

In [ ]:
model(X_train[0:3])

# set the initial weights to the params_fix that has been optimized layer by layer
# Note: please change the name of the keras layer accordingly based on the model.summary()
model.get_layer('keras_layer').set_weights([params_fix])

In [ ]:
opt = tf.keras.optimizers.Adam(learning_rate=0.05)
model.compile(opt, loss='mse', metrics=["accuracy"])

In [ ]:
# Note: please put the correct directory to save the weights accordingly if you want to run the code
filepath = "./Model/Best6_layer5(layer_id=all)_set5000_10epoch_saved-model-{epoch:02d}.hdf5"
checkpoint = tf.keras.callbacks.ModelCheckpoint(filepath, monitor='val_acc', verbose=1,
                                                save_weights_only=True, save_best_only=False, mode='auto')

In [ ]:
H = model.fit(X_train, to_categorical(Y_train), epochs=10, batch_size=128, initial_epoch=0,
              validation_data=(X_test, to_categorical(Y_test)), verbose=1,
              callbacks=[checkpoint])

In [ ]:
# load the parameters that is considered giving the best balance between train and test accuracy
model.load_weights('./Model/Best6_layer5(layer_id=all)_set5000_10epoch_saved-model-08.hdf5')


# keep the parameters as the best params, also keep the weight vector alpha
best_params = model.get_weights()[0]
alpha = model.get_weights()[1]

**Testing the Performance**

In [ ]:
best_params

In [ ]:
alpha 

In [ ]:
# view each of the layer's name and its specifications
model.summary()

In [ ]:
# load the parameters to the model
# Note: please change the name of the keras layer accordingly based on the model.summary()
model.get_layer('keras_layer').set_weights([best_params])
model.get_layer('class_weights').set_weights([np.array([alpha])])

In [ ]:
from sklearn.metrics import roc_auc_score

In [ ]:
#AUC for training set

Y_pred_train = model.predict(X_train)
roc_auc_score(Y_train, Y_pred_train[:, 1])

In [ ]:
#AUC for testing set

Y_pred_test = model.predict(X_test)
roc_auc_score(Y_test, Y_pred_test[:, 1])